#!/bin/sh

# Copyright (C) 2020-2025 Daniel Mueller <deso@posteo.net>
# SPDX-License-Identifier: GPL-3.0-or-later

set -e -o pipefail

SUBDIRECTORY_OK=1
source "$(git --exec-path)/git-sh-setup"

cd_to_toplevel
require_clean_work_tree $cmd

has_no_changes() {
  git diff --quiet --exit-code ${@}
}

revert_changes() {
  # We very likely have changes staged or unstaged. Revert them and then
  # move back to the original commit.
  git reset HEAD --hard --quiet
  git rebase --quiet "${head}"
  # Revert to default SIGINT handler and then resend signal. This
  # ensures that we exit with the "correct" exit code.
  trap - SIGINT
  kill -s INT "$$"
}

head=$(git rev-parse HEAD)
all_files="$(git show --no-prefix --name-only --format='' "${head}" | xargs)"

# Make sure to revert changes if the user cancels the operation or any
# command fails.
trap revert_changes SIGINT ERR

if [ $# -gt 0 ]; then
  add_files="$@"
else
  add_files="${all_files}"
fi
git reset HEAD^ --quiet
# The '--ignore-removal' option is necessary to correctly handle deleted
# files: without it those will already show up as staged, which means a
# later 'git add --patch' won't allow the user to modify them.
git add --ignore-removal --intent-to-add ${all_files}

while :; do
  # We use separate git add & git commit invocation because git commit
  # --patch prints undesirable status stuff when stopped directly with
  # 'q' without adding anything.
  git add --patch ${add_files}
  # Only attempt to commit something if the user staged changes.
  if ! has_no_changes --staged; then
    # On error, be sure to revert any staged changes to give the user a
    # chance to redo them.
    git commit --no-verify --reedit-message "${head}" \
      || git reset HEAD --quiet \
      || true
  fi

  if has_no_changes; then
    # If the user already included all changes then we are done.
    break
  fi

  while :; do
    echo -e "\n\e[1;34mDone splitting? (Y/n)\e[0m"
    read -s -n 1 done_
    case ${done_} in
      ""|"y"|"Y")
        git commit --no-verify --all --reedit-message "${head}" || continue
        exit
        ;;
      "n"|"N")
        break
        ;;
      *)
        echo "Response '${done_}' not understood."
        ;;
    esac
  done
done
